#!/usr/bin/expect -f
#exp_internal 1 #Used for expect debugging

set port [lindex $argv 0]
set ipaddr [lindex $argv 1]
eval spawn ssh -oHostKeyAlgorithms=+ssh-dss msfadmin@$ipaddr -y
expect "assword:" {send -- "msfadmin\r"}
expect "msfadmin@metasploitable:" {send -- "sudo su\r"}
expect "msfadmin:" {send -- "msfadmin\r"}
expect "root@metasploitable:/home/msfadmin# " {send -- "ufw allow $port\r"}
expect "root@metasploitable:/home/msfadmin# " {send -- "exit\r"}
exit


