#!/usr/bin/expect -f

#exp_internal 1 #Used for expect debugging
set timeout 5
set connected false
set passwordUsed ""
set idx 1

spawn ssh -oHostKeyAlgorithms=+ssh-dss msfadmin@192.168.1.181 -y
expect "assword:" {send -- "msfadmin\r"}
expect "msfadmin@metasploitable:" {send -- "sudo su\r"}
expect "msfadmin:" {send -- "msfadmin\r"}
expect "root@metasploitable:/home/msfadmin# " {send -- "sed -i "s/^anonymous_enable.*/anonymous_enable=NO/" /etc/vsftpd.config\r"}
expect eof